### PR TITLE
Amis car fixes. Added hook to cash register and shopping bags. Script store fixes. Possible Jokke Fix.

### PR DESCRIPTION
**Pull request by Athlon007**
- Fixed issues with Amis cars (again... This time permamently)
- Added a hook for cash register and shopping bags - now when you buy an item, or open a shopping bags, all new items will be added to the list of minor objects
- Modified how Store script works. Now it triggers different set of whitelist, if the player loaded game at Teimo's, and different for other places, because of issues regarding that list (maybe fixable?)
- Possible fix for Jokke (needs testing)
- Church wall is not unloaded anymore, to prevent Amis cars from driving into that area

### CODE REVIEW

**Comment by RedJohn260** [comment]
Btw, on
 ` ` `
private void PrepareForSaveGame()
` ` `
isKinematic should be like this:
` ` `
KINEMATIC.isKinematic = false;
` ` `
Because if it's true, car does not react to collisions and physics, and it should be saving with kinematic to false as it normally would.
So if you could change that would be great. I don't want to make a PR just for that.

**Comment by Athlon007** [comment]
Fixed.

**Comment by Krutonium** [comment]
smh Why is `isKinematic` opposite implied value.

Ready for Merge?

(Also FWIW if you could comment with ready for merge at the end of a PR, I would really appreciate it ^>^)

**Comment by RedJohn260** [comment]
I guess because the property of the component is ` ` ` isKinematic ` ` ` and not ` ` ` isKinematic.enabled ` ` ` so if ` ` ` isKinematic = true ` ` ` then it is Kinematic and if ` ` ` isKinematic = false ` ` ` then it's not Kinematic.

**Pull request merged**
