### PR TITLE
Added Satsumas Axles and Car Dynamics to disable on distance.

### PR DESCRIPTION
**Pull request by RedJohn260**
Added Satsumas Axles and Car Dynamics to disable on distance. Same as with Kinematic component.

### CODE REVIEW

**Comment by Krutonium** [comment]
This ready to go?

**Comment by RedJohn260** [comment]
Yes it is, just merged your new changes and added my changes on top of it.

**Comment by Krutonium** [comment]
So uh, someone came in with a PR that fixes cars entirely, SO... Sorry >.<

**Comment by RedJohn260** [comment]
Awesome, someone finally got interested in this.  Isn't satsuma is still as it is, still broken? And with disabling the additional components on it, there is a potential increase up to 5-10 fps. But whatever, i'll just keep that on my fork for now.

**Comment by Krutonium** [comment]
Yes, the satsuma is still broken, but every other vehicle works correctly now.

**Comment by Krutonium** [comment]
Okay so I have ported this to the new system, and merged it in - Thanks for the work <3

**Pull request closed without merging**
